// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const redirectUri =
        opts?.redirect_uri ||
        (typeof window !== "undefined" ? `${window.location.origin}/auth/callback` : undefined);

      // Try Lovable Cloud Auth if available
      try {
        const result = await lovableAuth.signInWithOAuth(provider, {
          redirect_uri: redirectUri,
          extraParams: {
            ...opts?.extraParams,
          },
        });

        if (result.redirected) {
          return result;
        }

        if (result.tokens) {
          await supabase.auth.setSession(result.tokens);
          return result;
        }

        if (result.error) {
          console.warn("[Auth] Lovable Cloud Auth failed, delegating to Supabase OAuth:", result.error);
        }
      } catch (err) {
        console.warn("[Auth] Lovable Auth exception, delegating to Supabase OAuth:", err);
      }

      // Direct Supabase OAuth Fallback (Standard Supabase JS SDK)
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: provider === "microsoft" ? "azure" : (provider as "google" | "apple" | "azure"),
        options: {
          redirectTo: redirectUri,
          queryParams: opts?.extraParams,
        },
      });

      if (error) {
        return { error: error instanceof Error ? error : new Error(error.message || String(error)) };
      }

      return { redirected: true, data };
    },
  },
};

